use super::*;

pub fn make_test_unit(kind: UnitKind, x: i32, y: i32) -> BattleUnit {
    BattleUnit {
        kind,
        x,
        y,
        facing: Direction::North,
        hanzi: "火",
        pinyin: "huo",
        speed: 4,
        movement: 3,
        stored_movement: 0,
        hp: 10,
        max_hp: 10,
        damage: 3,
        defending: false,
        alive: true,
        ai: AiBehavior::Chase,
        radical_actions: vec![],
        statuses: vec![],
        stunned: false,
        radical_armor: 0,
        radical_counter: false,
        marked_extra_damage: 0,
        thorn_armor_turns: 0,
        radical_dodge: false,
        radical_multiply: false,
        fortify_stacks: 0,
        boss_kind: None,
        is_decoy: false,
        word_group: None,
        word_group_order: 0,
        wuxing_element: None,
        intent: None,
        mastery_tier: 0,
        charge_remaining: None,
        synergy_damage_bonus: 0,
        elemental_resonance: false,
        sacrifice_bonus_damage: 0,
        sacrifice_bonus_turns: 0,
        momentum: 0,
        last_move_dir: None,
        first_strike_bonus: 0,
    }
}

pub fn make_test_battle(units: Vec<BattleUnit>) -> TacticalBattle {
    let turn_queue: Vec<usize> = (0..units.len()).collect();
    TacticalBattle {
        arena: TacticalArena::new(7, 7, ArenaBiome::StationInterior),
        units,
        turn_queue,
        turn_queue_pos: 0,
        phase: TacticalPhase::Command,
        turn_number: 1,
        combo_streak: 0,
        player_moved: false,
        player_acted: false,
        player_stance: PlayerStance::Balanced,
        typing_buffer: String::new(),
        typing_action: None,
        log: Vec::new(),
        last_answer: None,
        is_boss_battle: false,
        available_spells: Vec::new(),
        spell_cursor: 0,
        spell_menu_open: false,
        spent_spell_index: None,
        ward_tiles: Vec::new(),
        last_spell_school: None,
        last_spell_element: None,
        last_spell_turn: 0,
        combo_message: None,
        combo_message_timer: 0,
        combo_armor_bonus: 0,
        combo_armor_turns: 0,
        frozen_edge_charges: 0,
        stolen_spells: Vec::new(),
        player_class: None,
        available_items: Vec::new(),
        used_item_indices: Vec::new(),
        item_menu_open: false,
        item_cursor: 0,
        weather: Weather::Normal,
        terrain_tick_count: 0,
        focus: 10,
        max_focus: 10,
        radical_synergy_radical: None,
        radical_synergy_streak: 0,
        chengyu_history: Vec::new(),
        intents_calculated: false,
        player_radical_abilities: Vec::new(),
        consumed_radicals: Vec::new(),
        selected_radical_ability: None,
        radical_picker_open: false,
        radical_picker_cursor: 0,
        skill_menu_open: false,
        skill_menu_cursor: 0,
        projectiles: Vec::new(),
        arcing_projectiles: Vec::new(),
        god_mode: false,
        audio_events: Vec::new(),
        companion_kind: None,
        player_equip_effects: Vec::new(),
        attacks_on_player_this_round: 0,
        arena_event_timer: 3,
        pending_event: None,
        event_message: None,
        event_message_timer: 0,
        pending_impacts: Vec::new(),
        phase_walk_available: false,
        riposte_charges: 0,
        overcharge_active: false,
        hubris_mode: false,
        hard_answer_armor_bonus: 0,
        has_polyglot: false,
        has_linguists_fury: false,
        pending_skill_xp: 0,
        pending_weapon_crucible_xp: 0,
        pending_armor_crucible_xp: 0,
        pending_charm_crucible_xp: 0,
    }
}

