use std::collections::{HashMap, HashSet};
use std::env;
use std::fs;
use std::path::Path;

#[derive(Debug)]
struct VocabRow {
    hanzi: String,
    pinyin: String,
    meaning: String,
    hsk: u8,
}

fn main() {
    println!("cargo:rerun-if-changed=data/hsk30.csv");
    println!("cargo:rerun-if-changed=data/cedict_ts.u8");

    if let Err(err) = generate_vocab_data() {
        println!("cargo:warning=build.rs vocab generation warning: {}", err);
        if let Ok(out_dir) = env::var("OUT_DIR") {
            let out_path = Path::new(&out_dir).join("vocab_data.rs");
            let _ = fs::write(out_path, "pub static VOCAB: &[VocabEntry] = &[];\n");
        }
    }
}

fn generate_vocab_data() -> Result<(), String> {
    let cedict_map = load_cedict_map("data/cedict_ts.u8").unwrap_or_default();
    let csv = fs::read_to_string("data/hsk30.csv")
        .map_err(|e| format!("failed to read data/hsk30.csv: {e}"))?;

    let mut rows: Vec<VocabRow> = Vec::new();
    let mut seen_hanzi: HashSet<String> = HashSet::new();

    for (line_idx, line) in csv.lines().enumerate() {
        if line_idx == 0 {
            continue;
        }
        if line.trim().is_empty() {
            continue;
        }

        let cols = parse_csv_line(line);
        if cols.len() < 10 {
            continue;
        }

        let hanzi = cols.get(1).map(|s| s.trim()).unwrap_or("");
        if hanzi.is_empty() || !seen_hanzi.insert(hanzi.to_string()) {
            continue;
        }

        let pinyin_col = cols.get(3).map(|s| s.trim()).unwrap_or("");
        let pos_col = cols.get(4).map(|s| s.trim()).unwrap_or("");
        let level_col = cols.get(5).map(|s| s.trim()).unwrap_or("");
        let cedict_col = cols.get(9).map(|s| s.trim()).unwrap_or("");

        let hsk = map_hsk_level(level_col);
        // Convert the CSV diacritic pinyin for matching against CEDICT entries
        let csv_numbered = diacritic_pinyin_to_numbered(pinyin_col);

        let (dict_pinyin, dict_meaning) = if let Some(entries) = cedict_map.get(hanzi) {
            pick_best_cedict_entry(entries, &csv_numbered)
        } else {
            (String::new(), String::new())
        };

        let pinyin = if !dict_pinyin.is_empty() {
            dict_pinyin
        } else if let Some(from_ref) = extract_bracket_pinyin(cedict_col) {
            from_ref
        } else {
            csv_numbered.clone()
        };

        let meaning = if !dict_meaning.is_empty() {
            dict_meaning
        } else if !pos_col.is_empty() {
            pos_col.to_string()
        } else {
            String::new()
        };

        let (pinyin, meaning) = apply_compat_overrides(hanzi, pinyin, meaning);

        rows.push(VocabRow {
            hanzi: hanzi.to_string(),
            pinyin,
            meaning,
            hsk,
        });
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs; do not edit by hand.\n");
    out.push_str("pub static VOCAB: &[VocabEntry] = &[\n");
    for row in &rows {
        out.push_str("    VocabEntry { ");
        out.push_str("hanzi: \"");
        out.push_str(&escape_rust_string(&row.hanzi));
        out.push_str("\", ");
        out.push_str("pinyin: \"");
        out.push_str(&escape_rust_string(&row.pinyin));
        out.push_str("\", ");
        out.push_str("meaning: \"");
        out.push_str(&escape_rust_string(&row.meaning));
        out.push_str("\", ");
        out.push_str("hsk: ");
        out.push_str(&row.hsk.to_string());
        out.push_str(", ");
        out.push_str("example: \"\" },\n");
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").map_err(|e| format!("OUT_DIR not set: {e}"))?;
    let out_path = Path::new(&out_dir).join("vocab_data.rs");
    fs::write(out_path, out)
        .map_err(|e| format!("failed to write generated vocab_data.rs: {e}"))?;

    Ok(())
}

fn load_cedict_map(path: &str) -> Result<HashMap<String, Vec<(String, String)>>, String> {
    let content = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(_) => return Ok(HashMap::new()),
    };

    let mut map: HashMap<String, Vec<(String, String)>> = HashMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some((simplified, pinyin, meaning)) = parse_cedict_line(line) {
            map.entry(simplified).or_default().push((pinyin, meaning));
        }
    }
    Ok(map)
}

fn parse_cedict_line(line: &str) -> Option<(String, String, String)> {
    let first_space = line.find(' ')?;
    let second_space_rel = line[first_space + 1..].find(' ')?;
    let second_space = first_space + 1 + second_space_rel;

    let simplified = line[first_space + 1..second_space].trim();
    if simplified.is_empty() {
        return None;
    }

    let bracket_start = line[second_space + 1..].find('[')? + second_space + 1;
    let bracket_end = line[bracket_start + 1..].find(']')? + bracket_start + 1;

    let pinyin_spaced = line[bracket_start + 1..bracket_end].trim();
    let pinyin = normalize_numbered_pinyin(pinyin_spaced);

    let defs_part = line[bracket_end + 1..].trim();
    let meaning = first_real_definition(defs_part).unwrap_or_default();

    Some((simplified.to_string(), pinyin, meaning))
}

fn is_bad_meaning(meaning: &str) -> bool {
    let m = meaning.to_lowercase();
    m.starts_with("surname ")
        || m.starts_with("old variant of")
        || m.starts_with("variant of")
        || m.starts_with("see ")
        || m.starts_with("cl:")
}

fn looks_like_proper_noun_only(meaning: &str) -> bool {
    let trimmed = meaning.trim();
    if trimmed.is_empty() {
        return false;
    }
    let first_char = trimmed.chars().next().unwrap_or('a');
    if !first_char.is_ascii_uppercase() {
        return false;
    }
    !trimmed.contains(';') && !trimmed.contains("to ") && trimmed.split_whitespace().count() <= 3
}

fn pick_best_cedict_entry(entries: &[(String, String)], csv_pinyin: &str) -> (String, String) {
    let mut best: Option<&(String, String)> = None;
    let mut best_score: i32 = -1;

    for entry in entries {
        let mut score: i32 = 0;
        if !is_bad_meaning(&entry.1) {
            score += 10;
        }
        if entry.0 == csv_pinyin {
            score += 5;
        }
        if looks_like_proper_noun_only(&entry.1) {
            score -= 8;
        }
        if entry.1.contains(';') || entry.1.contains("to ") {
            score += 3;
        }
        if entry.1.len() > 2 {
            score += 1;
        }
        if score > best_score {
            best_score = score;
            best = Some(entry);
        }
    }

    match best {
        Some(e) => (e.0.clone(), e.1.clone()),
        None => (String::new(), String::new()),
    }
}

fn first_real_definition(defs_part: &str) -> Option<String> {
    let start = defs_part.find('/')?;
    let tail = &defs_part[start + 1..];
    let defs = tail.split('/').map(str::trim).filter(|d| !d.is_empty());

    let mut fallback: Option<String> = None;
    for d in defs {
        if fallback.is_none() {
            fallback = Some(d.to_string());
        }
        if d.starts_with("CL:") {
            continue;
        }
        if d.starts_with("variant of") || d.starts_with("old variant of") || d.starts_with("see ") {
            continue;
        }
        return Some(d.to_string());
    }
    fallback
}

fn parse_csv_line(line: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut current = String::new();
    let mut in_quotes = false;
    let mut chars = line.chars().peekable();

    while let Some(ch) = chars.next() {
        match ch {
            '"' => {
                if in_quotes && chars.peek() == Some(&'"') {
                    current.push('"');
                    let _ = chars.next();
                } else {
                    in_quotes = !in_quotes;
                }
            }
            ',' if !in_quotes => {
                fields.push(current.trim().to_string());
                current.clear();
            }
            _ => current.push(ch),
        }
    }
    fields.push(current.trim().trim_end_matches('\r').to_string());
    fields
}

fn map_hsk_level(level: &str) -> u8 {
    match level.trim() {
        "1" => 1,
        "2" => 2,
        "3" => 3,
        "4" => 4,
        "5" => 5,
        "6" => 6,
        "7-9" => 7,
        _ => 7,
    }
}

fn extract_bracket_pinyin(cedict_ref: &str) -> Option<String> {
    let start = cedict_ref.find('[')?;
    let end = cedict_ref[start + 1..].find(']')? + start + 1;
    let inner = cedict_ref[start + 1..end].trim();
    if inner.is_empty() {
        return None;
    }
    Some(normalize_numbered_pinyin(inner))
}

fn normalize_numbered_pinyin(pinyin: &str) -> String {
    pinyin
        .chars()
        .filter_map(|ch| {
            if ch.is_whitespace()
                || ch == '·'
                || ch == '•'
                || ch == '‧'
                || ch == '-'
                || ch == '–'
                || ch == '—'
                || ch == '\''
                || ch == ':'
            {
                None
            } else if ch == 'ü' || ch == 'Ü' {
                Some('v')
            } else {
                Some(ch.to_ascii_lowercase())
            }
        })
        .collect()
}

fn diacritic_pinyin_to_numbered(input: &str) -> String {
    input
        .split_whitespace()
        .filter_map(convert_token)
        .collect::<Vec<_>>()
        .join("")
}

/// Map a diacritic character to (base_ascii, optional_tone_digit).
fn map_diacritic(ch: char) -> Option<(char, Option<char>)> {
    let mapped = match ch {
        'ā' => ('a', Some('1')),
        'ē' => ('e', Some('1')),
        'ī' => ('i', Some('1')),
        'ō' => ('o', Some('1')),
        'ū' => ('u', Some('1')),
        'ǖ' => ('v', Some('1')),
        'á' => ('a', Some('2')),
        'é' => ('e', Some('2')),
        'í' => ('i', Some('2')),
        'ó' => ('o', Some('2')),
        'ú' => ('u', Some('2')),
        'ǘ' => ('v', Some('2')),
        'ǎ' => ('a', Some('3')),
        'ě' => ('e', Some('3')),
        'ǐ' => ('i', Some('3')),
        'ǒ' => ('o', Some('3')),
        'ǔ' => ('u', Some('3')),
        'ǚ' => ('v', Some('3')),
        'à' => ('a', Some('4')),
        'è' => ('e', Some('4')),
        'ì' => ('i', Some('4')),
        'ò' => ('o', Some('4')),
        'ù' => ('u', Some('4')),
        'ǜ' => ('v', Some('4')),
        'ü' | 'Ü' => ('v', None),
        'A'..='Z' | 'a'..='z' => (ch.to_ascii_lowercase(), None),
        _ => return None,
    };
    Some(mapped)
}

/// Convert a whitespace-separated token (which may contain multiple
/// concatenated pinyin syllables) into numbered pinyin.
/// E.g. "péngyoumen" → "peng2you5men5", "àihào" → "ai4hao4".
fn convert_token(raw: &str) -> Option<String> {
    // Pass 1: strip diacritics → plain ASCII, record tone for each position.
    let mut ascii = String::new();
    let mut tones: Vec<Option<char>> = Vec::new();
    let mut explicit_tone_digit: Option<char> = None;

    for ch in raw.chars() {
        if ('1'..='5').contains(&ch) {
            explicit_tone_digit = Some(ch);
            continue;
        }
        if let Some((base, tone)) = map_diacritic(ch) {
            tones.push(tone);
            ascii.push(base);
        }
    }

    if ascii.is_empty() {
        return None;
    }

    // If the token is a single syllable (has explicit digit or only one
    // syllable after splitting), use the old direct path for robustness.
    if let Some(digit) = explicit_tone_digit {
        return Some(format!("{}{}", ascii, digit));
    }

    // Pass 2: greedy longest-match split into valid pinyin syllables.
    let syllables = split_pinyin_syllables(&ascii);

    // Pass 3: assign tones to each syllable.
    let mut result = String::new();
    let mut pos = 0;
    for syl in &syllables {
        let syl_len = syl.len();
        let mut tone = None;
        for i in pos..pos + syl_len {
            if let Some(Some(t)) = tones.get(i) {
                tone = Some(*t);
            }
        }
        result.push_str(syl);
        result.push(tone.unwrap_or('5'));
        pos += syl_len;
    }

    if result.is_empty() {
        None
    } else {
        Some(result)
    }
}

/// Valid pinyin syllables (without tones) used for greedy splitting.
/// Listed longest-first so longest match wins.
fn pinyin_syllable_table() -> &'static [&'static str] {
    &[
        // 6-letter
        "zhuang", "shuang", "chuang", // 5-letter
        "zhuan", "zheng", "zhang", "zhuai", "zhong", "zhuan", "shuan", "sheng", "shang", "shuai",
        "shuai", "chuan", "cheng", "chang", "chuai", "chong", "guang", "huang", "kuang", "niang",
        "qiang", "xiang", "jiong", "qiong", "xiong", "liang", // 4-letter
        "zhan", "zhao", "zhei", "zhen", "zhai", "zhao", "zhou", "zhua", "shan", "shao", "shei",
        "shen", "shou", "shua", "shuo", "shai", "shao", "chan", "chao", "chen", "chou", "chua",
        "chui", "chun", "chuo", "chai", "bang", "beng", "bing", "biao", "cang", "ceng", "cong",
        "cuan", "dang", "deng", "ding", "dong", "dian", "diao", "duan", "fang", "feng", "fiao",
        "gang", "geng", "gong", "guan", "guai", "giao", "hang", "heng", "hong", "huan", "huai",
        "jian", "jiao", "jing", "juan", "jiang", "jiue", "kang", "keng", "kong", "kuan", "kuai",
        "lang", "leng", "ling", "long", "lian", "liao", "luan", "mang", "meng", "ming", "mian",
        "miao", "nang", "neng", "ning", "nong", "nian", "niao", "nuan", "pang", "peng", "ping",
        "pian", "piao", "qian", "qiao", "qing", "quan", "rang", "reng", "rong", "ruan", "sang",
        "seng", "song", "suan", "tang", "teng", "ting", "tong", "tian", "tiao", "tuan", "wang",
        "weng", "xian", "xiao", "xing", "xuan", "yang", "ying", "yong", "yuan", "zang", "zeng",
        "zong", "zuan", // 3-letter
        "zhi", "zhu", "zhe", "zha", "zhu", "shi", "shu", "she", "sha", "chi", "chu", "che", "cha",
        "bai", "ban", "bao", "bei", "ben", "bin", "cai", "can", "cao", "cei", "cen", "cou", "cui",
        "cun", "cuo", "dai", "dan", "dao", "dei", "den", "dia", "die", "diu", "dou", "dui", "dun",
        "duo", "fan", "fei", "fen", "fou", "gai", "gan", "gao", "gei", "gen", "gou", "gua", "gui",
        "gun", "guo", "hai", "han", "hao", "hei", "hen", "hou", "hua", "hui", "hun", "huo", "jia",
        "jie", "jin", "jiu", "jue", "jun", "kai", "kan", "kao", "kei", "ken", "kou", "kua", "kui",
        "kun", "kuo", "lai", "lan", "lao", "lei", "lia", "lie", "lin", "liu", "lou", "lun", "luo",
        "lve", "mai", "man", "mao", "mei", "men", "mie", "min", "miu", "mou", "nai", "nan", "nao",
        "nei", "nen", "nie", "nin", "niu", "nou", "nun", "nuo", "nve", "pai", "pan", "pao", "pei",
        "pen", "pie", "pin", "pou", "qia", "qie", "qin", "qiu", "que", "qun", "ran", "rao", "ren",
        "rou", "rua", "rui", "run", "ruo", "sai", "san", "sao", "sei", "sen", "sou", "sui", "sun",
        "suo", "tai", "tan", "tao", "tei", "tie", "tou", "tui", "tun", "tuo", "wai", "wan", "wei",
        "wen", "xia", "xie", "xin", "xiu", "xue", "xun", "yai", "yan", "yao", "yin", "you", "yue",
        "yun", "zai", "zan", "zao", "zei", "zen", "zou", "zui", "zun", "zuo", "ang", "eng",
        // 2-letter
        "ba", "bo", "bi", "bu", "ca", "ce", "ci", "cu", "da", "de", "di", "du", "fa", "fo", "fu",
        "ga", "ge", "gu", "ha", "he", "hu", "ji", "ju", "ka", "ke", "ku", "la", "le", "li", "lo",
        "lu", "lv", "ma", "me", "mi", "mo", "mu", "na", "ne", "ni", "nu", "nv", "pa", "pi", "po",
        "pu", "qi", "qu", "re", "ri", "ru", "sa", "se", "si", "su", "ta", "te", "ti", "tu", "wa",
        "wo", "wu", "xi", "xu", "ya", "ye", "yi", "yu", "za", "ze", "zi", "zu", "ai", "an", "ao",
        "ei", "en", "er", "ou", // 1-letter
        "a", "e", "o",
    ]
}

/// Greedy longest-match split of plain ASCII pinyin into syllables.
fn split_pinyin_syllables(ascii: &str) -> Vec<&str> {
    let table = pinyin_syllable_table();
    let mut syllables = Vec::new();
    let mut pos = 0;
    let bytes = ascii.as_bytes();

    while pos < bytes.len() {
        let remaining = &ascii[pos..];
        let mut matched = false;
        for &syl in table {
            if remaining.starts_with(syl) {
                syllables.push(&ascii[pos..pos + syl.len()]);
                pos += syl.len();
                matched = true;
                break;
            }
        }
        if !matched {
            pos += 1;
        }
    }

    syllables
}

fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn apply_compat_overrides(
    hanzi: &str,
    mut pinyin: String,
    mut meaning: String,
) -> (String, String) {
    match hanzi {
        "朋友" => {
            pinyin = "peng2you3".to_string();
            if meaning.is_empty() || meaning == "N" {
                meaning = "friend".to_string();
            }
        }
        "朋友们" => {
            pinyin = "peng2you3men5".to_string();
            if meaning.is_empty() || meaning == "N" {
                meaning = "friends".to_string();
            }
        }
        "对不起" => {
            pinyin = "dui4bu4qi3".to_string();
            if meaning.is_empty() {
                meaning = "sorry".to_string();
            }
        }
        "谢谢" => {
            if pinyin.is_empty() {
                pinyin = "xie4xie4".to_string();
            }
            if meaning.is_empty() {
                meaning = "thanks".to_string();
            }
        }
        _ => {}
    }
    (pinyin, meaning)
}
