// Auto-generated verified recipes from hanzicraft.com
// Run: python tools/verify_recipes.py --generate

pub const RECIPES: &[Recipe] = &[
    Recipe { inputs: &["日", "月"], output_hanzi: "明", output_pinyin: "Ming2", output_meaning: "Ming Dynasty (1368-1644)", effect: SpellEffect::FireAoe(3) },
    Recipe { inputs: &["女", "子"], output_hanzi: "好", output_pinyin: "hao3", output_meaning: "good", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["山", "石"], output_hanzi: "岩", output_pinyin: "yan2", output_meaning: "cliff", effect: SpellEffect::Shield },
    Recipe { inputs: &["口", "马"], output_hanzi: "吗", output_pinyin: "ma3", output_meaning: "see 嗎啡|吗啡, morphine", effect: SpellEffect::Stun },
    Recipe { inputs: &["口", "贝"], output_hanzi: "呗", output_pinyin: "bai4", output_meaning: "to chant", effect: SpellEffect::Drain(3) },
    Recipe { inputs: &["木", "子"], output_hanzi: "李", output_pinyin: "Li3", output_meaning: "surname Li", effect: SpellEffect::Heal(3) },
    Recipe { inputs: &["木", "口"], output_hanzi: "杏", output_pinyin: "xing4", output_meaning: "apricot", effect: SpellEffect::Heal(3) },
    Recipe { inputs: &["小", "土"], output_hanzi: "尘", output_pinyin: "chen2", output_meaning: "dust", effect: SpellEffect::Shield },
    Recipe { inputs: &["石", "马"], output_hanzi: "码", output_pinyin: "ma3", output_meaning: "weight", effect: SpellEffect::Stun },
    Recipe { inputs: &["王", "田", "土"], output_hanzi: "理", output_pinyin: "li3", output_meaning: "texture", effect: SpellEffect::Shield },
    Recipe { inputs: &["田", "力"], output_hanzi: "男", output_pinyin: "nan2", output_meaning: "male", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["火", "虫"], output_hanzi: "烛", output_pinyin: "zhu2", output_meaning: "candle", effect: SpellEffect::FireAoe(3) },
    Recipe { inputs: &["力", "口"], output_hanzi: "加", output_pinyin: "Jia1", output_meaning: "abbr. for Canada 加拿大[Jia1 na2 da4]", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["口", "鸟"], output_hanzi: "鸣", output_pinyin: "ming2", output_meaning: "to cry (of birds)", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["女", "马"], output_hanzi: "妈", output_pinyin: "ma1", output_meaning: "ma", effect: SpellEffect::Stun },
    Recipe { inputs: &["竹", "木", "目"], output_hanzi: "箱", output_pinyin: "xiang1", output_meaning: "box", effect: SpellEffect::Heal(4) },
    Recipe { inputs: &["女", "口"], output_hanzi: "如", output_pinyin: "ru2", output_meaning: "as", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["木", "目", "心"], output_hanzi: "想", output_pinyin: "xiang3", output_meaning: "to think", effect: SpellEffect::Heal(4) },
    Recipe { inputs: &["雨", "田"], output_hanzi: "雷", output_pinyin: "Lei2", output_meaning: "surname Lei", effect: SpellEffect::FireAoe(3) },
    Recipe { inputs: &["手", "目"], output_hanzi: "看", output_pinyin: "kan1", output_meaning: "to look after", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["田", "心"], output_hanzi: "思", output_pinyin: "si1", output_meaning: "to think", effect: SpellEffect::Heal(3) },
    Recipe { inputs: &["刀", "口"], output_hanzi: "召", output_pinyin: "Shao4", output_meaning: "surname Shao", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["口", "王"], output_hanzi: "呈", output_pinyin: "cheng2", output_meaning: "to present to a superior", effect: SpellEffect::Shield },
    Recipe { inputs: &["口", "日"], output_hanzi: "唱", output_pinyin: "chang4", output_meaning: "to sing", effect: SpellEffect::FireAoe(3) },
    Recipe { inputs: &["田", "木"], output_hanzi: "果", output_pinyin: "guo3", output_meaning: "fruit", effect: SpellEffect::Heal(3) },
    Recipe { inputs: &["木", "风"], output_hanzi: "枫", output_pinyin: "feng1", output_meaning: "maple", effect: SpellEffect::Heal(3) },
    Recipe { inputs: &["力", "口", "木"], output_hanzi: "架", output_pinyin: "jia4", output_meaning: "to support", effect: SpellEffect::Heal(4) },
    Recipe { inputs: &["木", "米", "女"], output_hanzi: "楼", output_pinyin: "lou2", output_meaning: "house with more than 1 story", effect: SpellEffect::Heal(4) },
    Recipe { inputs: &["火", "山"], output_hanzi: "灿", output_pinyin: "can4", output_meaning: "glorious", effect: SpellEffect::FireAoe(3) },
    Recipe { inputs: &["土", "人"], output_hanzi: "坐", output_pinyin: "Zuo4", output_meaning: "surname Zuo", effect: SpellEffect::Shield },
    Recipe { inputs: &["日", "王"], output_hanzi: "旺", output_pinyin: "wang4", output_meaning: "prosperous", effect: SpellEffect::FireAoe(3) },
    Recipe { inputs: &["山", "风"], output_hanzi: "岚", output_pinyin: "lan2", output_meaning: "mist", effect: SpellEffect::Shield },
    Recipe { inputs: &["山", "月"], output_hanzi: "崩", output_pinyin: "beng1", output_meaning: "to collapse", effect: SpellEffect::Heal(3) },
    Recipe { inputs: &["雨", "木", "目"], output_hanzi: "霜", output_pinyin: "shuang1", output_meaning: "frost", effect: SpellEffect::FireAoe(4) },
    Recipe { inputs: &["人", "王"], output_hanzi: "全", output_pinyin: "Quan2", output_meaning: "surname Quan", effect: SpellEffect::Shield },
    Recipe { inputs: &["米", "大"], output_hanzi: "类", output_pinyin: "lei4", output_meaning: "kind", effect: SpellEffect::Heal(3) },
    Recipe { inputs: &["力", "口", "贝"], output_hanzi: "贺", output_pinyin: "He4", output_meaning: "surname He", effect: SpellEffect::StrongHit(4) },
    Recipe { inputs: &["虫", "马"], output_hanzi: "蚂", output_pinyin: "ma1", output_meaning: "dragonfly", effect: SpellEffect::Drain(3) },
    Recipe { inputs: &["竹", "马"], output_hanzi: "笃", output_pinyin: "du3", output_meaning: "serious (illness)", effect: SpellEffect::Stun },
    Recipe { inputs: &["月", "田", "心"], output_hanzi: "腮", output_pinyin: "sai1", output_meaning: "cheek", effect: SpellEffect::Heal(4) },
    Recipe { inputs: &["火", "土"], output_hanzi: "灶", output_pinyin: "zao4", output_meaning: "kitchen stove", effect: SpellEffect::FireAoe(3) },
    Recipe { inputs: &["木", "火"], output_hanzi: "焚", output_pinyin: "fen2", output_meaning: "to burn", effect: SpellEffect::FireAoe(3) },
];